<main id="convocations">
    <h1>Convocations</h1>

    <section>
        <input type="search">
        <input type="submit" value="Rechercher">
        <select>
            <option>Tri par poste</option>
            <option>Gardiens</option>
            <option>Défenseurs</option>
            <option>Milieu</option>
            <option>Attaquants</option>
        </select>
        <table>
            <thead>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Poste</th>
            </thead>
            <tbody>
                <tr>
                    <td>Joueur 1</td>
                    <td>Nom</td>
                    <td>Defenseur</td>
                </tr>
                <tr>
                    <td>Joueur 1</td>
                    <td>Nom</td>
                    <td>Defenseur</td>
                </tr>
                <tr>
                    <td>Joueur 1</td>
                    <td>Nom</td>
                    <td>Defenseur</td>
                </tr>
                <tr>
                    <td>Joueur 1</td>
                    <td>Nom</td>
                    <td>Defenseur</td>
                </tr>
                <tr>
                    <td>Joueur 1</td>
                    <td>Nom</td>
                    <td>Defenseur</td>
                </tr>
            </tbody>
        </table>
    </section>

    <section>
        <h2>Info Rencontre : </h2>
        <label>Date</label>
        <input type="text">

        <label>Lieu : </label>
        <input type="text">

        <label>Équipe Adverse : </label>
        <input type="text">

        <label>Heure de Rdv : </label>
        <input type="text">

        <label>Lieu de Rdv : </label>
        <input type="text">
    </section>
    <section>
        <h3>Convoqués :</h3>
        <table>
            <thead>
                <th>N°</th>
                <th>Nom</th>
                <th>Prenom</th>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>7</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>8</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>9</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>10</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>11</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>12</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>13</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
                <tr>
                    <td>14</td>
                    <td>Nom</td>
                    <td>Prenom</td>
                </tr>
            </tbody>
        </table>
    </section>
</main>