<main id="effectif">
<button>< Equipes</button>
<h1>Effectif</h1>
    <nav>
        <ul>
            <li>Gardiens</li>
            <li>Defenseurs</li>
            <li>Milieu</li>
            <li>Attaquants</li>
        </ul>
    </nav>
    
    <section>
        <h2>Gardien</h2>
        <ul>
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="" alt="photo du joueur">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
            
            <li>
                <article>
                    <header>
                        <figure>
                            <img src=""  alt="photo du joueur">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
            
            <li>
                <article>
                    <header>
                        <figure>
                            <img src=""  alt="photo du joueur">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
        </ul>
        
        
        <h2>DEfenseur</h2>
        <ul>
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
            
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
            
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
        </ul>
        
        <h2>Milieu</h2>
        <ul>
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
            
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
            
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
        </ul>
        
        <h2>Attaquant</h2>
        <ul>
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
            
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
            
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="">
                        </figure>
                    </header>
                    <main>
                        <h3>arnaud deletre</h3>
                        <p>grtrhyg</p>
                    </main>
                    <button>voir joueur</button>
                </article>
            </li>
        </ul>
    </section>
</main>