<main id="home">
    <figure>
        <img src="">
    </figure>

    <section>
        <section>
            <h2>Dernier Résultat</h2>
        </section>
        <section>
            <h2>Prochain match</h2>
        </section>
    </section>

    <section>
        <section>
            <h2>Article le plus récent</h2>
        </section>
        <section>
            <h2>Autres articles</h2>
        </section>
        <button>Voir Plus</button>
    </section>
    
    <section>
        <section>
            <h2>Album1</h2>
        </section>
        
        <section>
            <h2>Album2</h2>
        </section>
        <button>Voir Albums</button>
    </section>
</main>