<main id="allTeams">
    <figure>
        <img src="" alt="logo">
    </figure>
    <h1>Toutes les équipes</h1>
    <section>
        <h3>Séniors</h3>
        <button>Voir effectif</button>
        <section>
            <ul>
                <li>
                    <article>
                        <header>
                            <figure>
                                <img src="" alt="photo d'équipe">
                            </figure>
                        </header>
                        <main>
                    
                        </main>
                    </article>
                </li>
            </ul>
        </section>
    </section>
    <section>
        <h3>Vétérans</h3>
        <button>Voir effectif</button>
        <section>
            <ul>
                <li>
                    <article>
                        <header>
                            <figure>
                                <img src="" alt="photo d'équipe">
                            </figure>
                        </header>
                        <main>
                    
                        </main>
                    </article>
                </li>
            </ul>
        </section>
    </section>
    <section>
        <h3>Jeunes</h3>
        <button>Voir effectif</button>
        <section>
            <ul>
                <li>
                    <article>
                        <header>
                            <figure>
                                <img src="" alt="photo d'équipe">
                            </figure>
                        </header>
                        <main>
                    
                        </main>
                    </article>
                </li>
            </ul>
        </section>
    </section>
</main>