<main>
    <h1>Joueurs</h1>

    <table>
        <thead>
            <th></th>
        </thead>
        <tbody>
            <?php foreach($data as $players){ ?>
            <tr>
                <td><?= $this->playerManager->getFirstname() ?></td>
                <td><?= $this->playerManager->getLastname()?></td>
                <td><?= $this->playerManager->getPhone()?></td>
                <td><?= $this->playerManager->getBirthdate()?></td>
                <td><?= $this->playerManager->getPosition()?></td>
                <td><?= $this->playerManager->getFoot()?></td>
                <td><?= $this->playerManager->getBio()?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <h2>Ajouter un joueur</h2>
    <form method="POST" action="admin-players">

        <label>Image de profil</label>
        <input type="file" name="playerPics">

        <label>Prénom</label>
        <input type="text" name="playerFirstname">

        <label>Nom</label>
        <input type="text" name="playerLastname">

        <label>Phone</label>
        <input type="text" name="playerPhone">

        <label>Date de naissance</label>
        <input type="date" name="playerBirthdate">

        <label>Poste</label>
        <select name="playerPosition">
            <option>--Poste--</option>
            <option>Gardiens</option>
            <option>Défenseur</option>
            <option>Milieu</option>
            <option>Attaquant</option>
        </select>

        <label>Pied Fort</label>
        <select name="playerFoot">
            <option>--Pied Fort--</option>
            <option>Droit</option>
            <option>Gauche</option>
        </select>

        <label>Bio</label>
        <textarea name="playerBio"></textarea>
        <input type="submit" value="Ajouter">
    </form>
</main>