<main>
    <?php var_dump($data['player']);?>
    <h1>Modifier Joueur</h1>
<form method="post" name="editPlayerForm" action="/res03-projet-final/ProjetPerso/admin/admin-players/admin-player-edit/<?= $data['player']->getId(); ?>">
    <fieldset>
    <label>Prénom</label>
    <input type="text" name="editFirstname" value="<?= $data['player']->getFirstname()?>">
    </fieldset>
    <fieldset>
    <label>Nom</label>
    <input type="text" name="editLastname" value="<?= $data['player']->getLastname()?>">
    </fieldset>
    <fieldset>
    <label>Phone</label>
    <input type="text" name="editPhone" value="<?= $data['player']->getPhone()?>">
    </fieldset>
    
    <fieldset>
    <label>Date de naissance</label>
    <input type="date" name="editBirthdate" value="<?= $data['player']->getBirthdate() ?>" >
    </fieldset>
    
    <fieldset>
    <label>Poste</label>
    <select name="editPosition" value="<?= $data['player']->getPosition()?>">
        <option>Gardiens</option>
        <option>Défenseur</option>
        <option>Milieu</option>
        <option>Attaquant</option>
    </select>
    </fieldset>
    
    <fieldset>
    <label>Pied Fort</label>
    <select name="editFoot" value="<?= $data['player']->getFoot()?>">
        <option>Droit</option>
        <option>Gauche</option>
    </select>
    </fieldset>
    
    <fieldset>
    <label>Bio</label>
    <input type="textarea" name="editBio" value="<?= $data['player']->getBio(); ?>">
    </fieldset>
    
    <fieldset>
    <label>Image de profil</label>
    <input type="text" name="editProfilImg">
    </fieldset>
    <fieldset>
    <label>Catégorie</label>
        <select name="editPlayerCategory">
            <option value="<?=$data['player']->getCategoryId(); ?>" >Catégorie Actuelle</option>
        </select>
    </fieldset>
    
    
    
    <input type="submit" value="Modifier" name="editBtn">
</form>
</main>
