<main id="convocations">
    <h1>Convocations</h1>

    <section>
        <h2>Info Rencontre : </h2>
        <label>Date</label>
        <input type="text">

        <label>Lieu : </label>
        <input type="text">

        <label>Équipe Adverse : </label>
        <input type="text">

        <label>Heure de Rdv : </label>
        <input type="text">

        <label>Lieu de Rdv : </label>
        <input type="text">
    </section>
    <section>
        <h3>Convoqués :</h3>
        <table>
            <thead>
                <th>N°</th>
                <th>Joueur</th>
            </thead>
            <tbody>
                <tr>
                    <td>1</td> 
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>3</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>4</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>5</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>6</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>7</td>
                    <td> 
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>8</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                         </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>9</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>10</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>11</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>12</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>13</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>14</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?>, <?= $player->getPosition() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
    </section>
</main>