<main id="admin-convocations">
    <h1>Convocations</h1>
    <form>
    <section>
        <h2>Info Rencontre : </h2>
        <label>Date</label>
        <input type="text">

        <label>Lieu :

        <label>Équipe Adverse : </label>
        <input type="text">

        <label>Heure de Rdv : </label>
        <input type="text">

        <label>Lieu de Rdv : </label>
        <input type="text">
    </section>
    <section>
        <h3>Convoqués :</h3>
        <table>
            <thead>
                <th>N°</th>
                <th>Joueur</th>
            </thead>
            <tbody>
                <tr>
                    <td>1</td> 
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°1"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°2"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>3</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°3"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>4</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°4"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>5</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°5"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>6</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°6"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>7</td>
                    <td> 
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°7"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>8</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°8"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                         </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>9</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°9"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>10</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°10"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>11</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°11"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>12</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°12"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>13</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°13"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                    
                </tr>
                <tr>
                    <td>14</td>
                    <td>
                        <select>
                            <option value="">--- Choisir un joueur ---</option>
                            <?php foreach($data['players'] as $player){ ?>
                            <option name="n°14"><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
                            <?php } ?>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
    </section>
    </form>
</main>