<section id="registerForm">
    <h2 class="sr-only">Formulaire d'ajout admin</h2>
    <section>
    <h2>S'inscrire</h2>
    <form action="register" method="post">

        <fieldset>
        <label>Email : </label>
        </fieldset>
        
        <fieldset>
        <input type="email" name="registerEmail">
        </fieldset>
        
        <fieldset>
        <label>Mot de passe : </label>
        </fieldset>
        <fieldset>
        <input type="password" name="registerPassword">
        </fieldset>
        
        <fieldset>
        <label>Confirmer Mot de passe : </label>
        </fieldset>
        <fieldset>
        <input type="password" name="confirmPassword">
        </fieldset>
        
        <input type="submit" name="register" value="Créer un admin" id="registerButton">
    </form>
    </section>
</section>