<main>
    <h1>Modifier articles</h1>
    <form method="post" action="/res03-projet-final/ProjetPerso/admin/admin-posts/admin-post-edit/<?= $data['article']->getId(); ?>">
    
        <label>Photo</label>
        <input type="text" name="articleEditPicture" value="">
    
        <label>Titre</label>
        <input type="text" name="articleEditTitle" value="<?= $data['article']->getTitle() ?>">
        
        <label>Description</label>
        <input type="text" name="articleEditDescription" value="<?= $data['article']->getDescription() ?>">
        
        <label>Contenu</label>
        <input type="text" name="articleEditContent" value="<?= $data['article']->getContent() ?>">
    
        <input type="submit" value="Modifier">
    </form>
</main>