<main id="admin-players">
    <h1>Joueurs</h1>

    <table class="table table-sm">
        <thead>
            <th scope="col">Prénom</th>
            <th scope="col">Nom</th>
            <th scope="col">Tel</th>
            <th scope="col">Date de naissance</th>
            <th scope="col">Poste</th>
            <th scope="col">Pied fort</th>
            <th scope="col">Bio</th>
            <th scope="col">Actions</th>
        </thead>
        <tbody>
            <?php 
            foreach($data['players'] as $player){ ?>
            <tr>
                <td><?= $player->getFirstname() ?></td>
                <td><?= $player->getLastname()?></td>
                <td><?= $player->getPhone()?></td>
                <td><?= $player->getBirthdate()?></td>
                <td><?= $player->getPosition()?></td>
                <td><?= $player->getFoot()?></td>
                <td><?= $player->getBio()?></td>
                <td><a href="/res03-projet-final/ProjetPerso/admin/admin-players/admin-player-edit/<?= $player->getId();?>">Modifier</a> <a href="/res03-projet-final/ProjetPerso/admin/admin-players/admin-player-delete/<?= $player->getId();?>">Supprimer</a></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <h2>Ajouter un joueur</h2>
    <form method="post" action="admin-players" name="formPlayerAdd">

        <fieldset>
            <label>Image de profil</label>
            <input type="text" name="playerPics">
        </fieldset>
            
        <fieldset>
            <label>Prénom</label>
            <input type="text" name="playerFirstname">
        </fieldset>
            
        <fieldset>
            <label>Nom</label>
            <input type="text" name="playerLastname">
        </fieldset>
        
        <fieldset>
            <label>Phone</label>
            <input type="text" name="playerPhone">
        </fieldset>
        
        <fieldset>
            <label>Date de naissance</label>
            <input type="date" name="playerBirthdate">
        </fieldset>
        
        <fieldset>
            <label>Poste</label>
            <select name="playerPosition">
                <option>--Poste--</option>
                <option>Gardien</option>
                <option>Défenseur</option>
                <option>Milieu</option>
                <option>Attaquant</option>
            </select>
        </fieldset>
            
        <fieldset>
            <label>Pied Fort</label>
            <select name="playerFoot">
                <option>--Pied Fort--</option>
                <option>Droit</option>
                <option>Gauche</option>
            </select>
        </fieldset>
            
        <fieldset>
            <label>Bio</label>
            <textarea name="playerBio"></textarea>
        </fieldset>
            
        <fieldset>
            <label>Catégorie</label>
            <select name="playerCategory">
                <option>--Catégorie--</option>
                <?php 
                foreach($data['category'] as $category){ ?>
                <option value="<?= $category->getId() ?>"><?= $category->getName() ?></option>
                <?php } ?>
            </select>
        </fieldset>
        
        <input type="submit" value="Ajouter">
        
        
    </form>
</main>