<h1>Modifier Joueur</h1>
<form method="POST">
    
    <label>Image de profil</label>
    <input type="file">
    
    <label>Prénom</label>
    <input type="text">
    
    <label>Nom</label>
    <input type="text">
    
    <label>Phone</label>
    <input type="text">
    
    <label>Poste</label>
    <select>
        <option>--Poste--</option>
        <option>Gardiens</option>
        <option>Défenseur</option>
        <option>Milieu</option>
        <option>Attaquant</option>
    </select>
    
    <label>Pied Fort</label>
    <select>
        <option>--Pied Fort--</option>
        <option>Droit</option>
        <option>Gauche</option>
    </select>
    
    <label>Bio</label>
    <input type="textarea">
    <input type="submit" value="Modifier">
</form>