<main id="admin-convocations">
    <h1>Convocations</h1>
    
    <section>
        <form method="post" action="admin-convocation">
        <h2>Info Rencontre : </h2>
        <label for="date">Date</label>
        <input type="text" name="dateMatch">

        <label for="lieu">Lieu :</label>
        <input type="text" name="lieuMatch">

        <label for="equipeAdverse">Équipe Adverse : </label>
        <input type="text" name="equipeAdverse">

        <label for="rdvMatch">Heure de Rdv : </label>
        <input type="text"  name="rdvMatch">

        <label for="lieuRdvMatch">Lieu de Rdv : </label>
        <input type="text" name="lieuRdvMatch">
        
        <h3>Convoqués :</h3>
        
        <label for="n°1">1</label>
        <select name="n°1">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°2">2</label>
        <select name="n°2">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°1">3</label>
        <select name="n°3">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°4">4</label>
        <select name="n°4">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°5">5</label>
        <select name="n°5">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°6">6</label>
        <select name="n°6">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°7">7</label>
        <select name="n°7">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°8">8</label>
        <select name="n°8">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°9">9</label>
        <select name="n°9">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°10">10</label>
        <select name="n°10">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°11">11</label>
        <select name="n°11">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°12">12</label>
        <select name="n°12">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°13">13</label>
        <select name="n°13">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <label for="n°14">14</label>
        <select name="n°14">
            <option value="">--- Choisir un joueur ---</option>
            <?php foreach($data['players'] as $player){ ?>
            <option><?= $player->getFirstname() ?> <?= $player->getLastname() ?></option>
            <?php } ?>
        </select>
        
        <input type="submit">
    </form>
    </section>
    
</main>