<main>
    <h1>Staff</h1>

    <table class="table table-sm">
        <thead>
            <th scope="col">Id</th>
            <th scope="col">Prénom</th>
            <th scope="col">Nom</th>
            <th scope="col">Tel</th>
            <th scope="col">Role</th>
            <th scope="col">Actions</th>
        </thead>
        <tbody>
            <?php 
            foreach($data['staff'] as $staff){ ?>
            <tr>
                <td><?= $staff->getId() ?></td>
                <td><?= $staff->getFirstname() ?></td>
                <td><?= $staff->getLastname()?></td>
                <td><?= $staff->getPhone()?></td>
                <td><?= $staff->getRole()?></td>
                <td><a href="/res03-projet-final/ProjetPerso/admin/admin-staff/admin-staff-edit/<?= $staff->getId();?>">Modifier</a><a href="/res03-projet-final/ProjetPerso/admin/admin-staff/admin-staff-delete/<?= $staff->getId();?>">Supprimer</a></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
    <h2>Ajouter un membre du staff</h2>
    <form method="post" action="admin-staff" name="formStaffAdd">
        
        <fieldset>
            <label>Prénom</label>
            <input type="text" name="staffFirstname">
        </fieldset>
            
        <fieldset>
            <label>Nom</label>
            <input type="text" name="staffLastname">
        </fieldset>
        
        <fieldset>
            <label>Phone</label>
            <input type="text" name="staffPhone">
        </fieldset>
        
        <fieldset>
            <label>Role</label>
            <input type="text" name="staffRole">
        </fieldset>
        
        <fieldset>
            <label>Image de profil</label>
            <input type="text" name="staffProfilImg">
        </fieldset>
        
        
        <input type="submit" value="Ajouter">
        
        
    </form>
</main>