<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Arnaud Deletre" >
    <meta name="referrer" content="origin" >
    <meta name="title" content="US Sainte-Marie">
    <meta name="keywords" content="Football, Sainte-Marie, District, Bleu, 35, Redon">
    <meta property="og:site_name" content="US Sainte-Marie">
    <meta property="og:title" content="US Sainte-Marie">
    <meta property="og:type" content="article">
    <meta property="og:url" content="https://arnauddeletre.sites.3wa.io/res03-projet-final/ProjetPerso/">
    <meta property="og:image" content="/res03-projet-final/ProjetPerso/assets/img/backgrd_USSM.jpg">
    <meta property="og:description" content="Site officiel du club de foot de l'US Sainte-Marie">
    <meta property="og:locale" content="fr_FR">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="res03-projet-final/ProjetPerso/assets/styles/css/style.css">
    <script src="https://kit.fontawesome.com/59bf7db22b.js" crossorigin="anonymous"></script>
    <title>US Sainte-Marie</title>
</head>

<body id="admin">
    
    <!--HEADER-->
    <?php
        require 'templates/partials/_adminNav.phtml'
    ?>
    
    <!--MAIN-->
    <?php 
        require "templates/admin/".$template.".phtml"; 
    ?>
</body>

</html>