<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Arnaud Deletre" >
    <meta name="referrer" content="origin" >
    <meta name="title" content="US Sainte-Marie">
    <meta name="keywords" content="Football, Sainte-Marie, District, Bleu, 35, Redon">
    <meta property="og:site_name" content="US Sainte-Marie">
    <meta property="og:title" content="US Sainte-Marie">
    <meta property="og:type" content="article">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta property="og:locale" content="fr_FR">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="res03-projet-final/ProjetPerso/assets/styles/css/style.css">
    <title>US Sainte-Marie</title>
</head>

<body id="admin">
    
    <!--HEADER-->
    <?php
        require 'templates/partials/_adminNav.phtml'
    ?>
    
    <!--MAIN-->
    <?php 
        require "templates/admin/".$template.".phtml"; 
    ?>
</body>

</html>