<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Arnaud Deletre" />
    <meta name="referrer" content="origin" />
    <meta name="title" content="US Sainte-Marie">
    <meta name="keywords" content="Football, Sainte-Marie, District, Bleu, 35, Redon">
    <meta property="og:site_name" content="US Sainte-Marie">
    <meta property="og:title" content="US Sainte-Marie">
    <meta property="og:type" content="article">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta property="og:locale" content="fr_FR">
    <link rel="stylesheet" href="assets/styles/css/style.css">
    <title>US Sainte-Marie</title>
</head>

<body id="public">
    
    <!--HEADER-->
    <?php
        require 'templates/partials/_publicNav.phtml'
    ?>
    
    <!--MAIN-->
    <h2>PUBLIC LAYOUT</h2>
    <?php 
        require "templates/public/$template.phtml"; 
    ?>
    
    <!--FOOTER-->
    <?php
        require 'templates/partials/_footer.phtml'
    ?>
</body>

</html>