<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Arnaud Deletre" >
    <meta name="referrer" content="origin" >
    <meta name="title" content="US Sainte-Marie">
    <meta name="keywords" content="Football, Sainte-Marie, District, Bleu, 35, Redon">
    <meta property="og:site_name" content="US Sainte-Marie">
    <meta property="og:title" content="Site de l'US Sainte-Marie">
    <meta property="og:type" content="article">
    <meta property="og:url" content="https://arnauddeletre.sites.3wa.io/res03-projet-final/ProjetPerso/">
    <meta property="og:image" content="https://def773hwqc19t.cloudfront.net/actor_logo/1238/1f975aba91e019e7e80f4b6a81764632_U_S_S_M___.png">
    <meta property="og:description" content="Site officiel du club de foot de l'US Sainte-Marie">
    <meta property="og:locale" content="fr_FR">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/res03-projet-final/ProjetPerso/assets/styles/css/style.css">
    <script src="https://kit.fontawesome.com/59bf7db22b.js" crossorigin="anonymous"></script>
    <title>US Sainte-Marie</title>
</head>

<body id="public">
    <h1 class="sr-only">Site Officiel US Sainte-Marie</h1>
    <!--HEADER-->
    <?php
        require 'templates/partials/_publicNav.phtml'
    ?>
    
    <!--MAIN-->
    <?php 
        require "templates/public/$template.phtml"; 
    ?>
    
    <!--FOOTER-->
    <?php
        require 'templates/partials/_footer.phtml'
    ?>
    <script src="/res03-projet-final/ProjetPerso/assets/styles/js/main.js"></script>
</body>

</html>