<header>
    <nav>
        <h2 class="sr-only">Nav Admin</h2>
        <figure>
            <a href="/res03-projet-final/ProjetPerso/admin"><img src="../assets/img/ecusson.jpg"></a>
        </figure>
        <ul>
            <li>
                <a href="">Joueurs</a>
            </li>
            
            <li>
                <a href="">Staff</a>
            </li>
            
            <li>
                <a href="">Articles</a>
            </li>
            
            <li>
                <a href="">Photos</a>
            </li>
            
            <li>
                <a href="">Convocations</a>
            </li>
        </ul>
    </nav>
</header>