<header>
    <nav>
        <h2 class="sr-only">Nav Admin</h2>
        <figure>
            <a href=""><img src=""></a>
        </figure>
        <ul>
            <li>
                <a href="/res03-projet-final/ProjetPerso/admin/admin-players">Joueurs</a>
            </li>
            
            <li>
                <a href="/res03-projet-final/ProjetPerso/admin/admin-staff">Staff</a>
            </li>
            
            <li>
                <a href="/res03-projet-final/ProjetPerso/admin/admin-articles">Articles</a>
            </li>
            
            <li>
                <a href="/res03-projet-final/ProjetPerso/admin/admin-photo">Photos</a>
            </li>
            
            <li>
                <a href="/res03-projet-final/ProjetPerso/admin/admin-convocation">Convocations</a>
            </li>
        </ul>
    </nav>
</header>