<footer>
    <!--gridcolumn:3, gridrow:3-->
    <h2>US SAINTE-MARIE</h2>
    <!--colum1, row1/3-->

    <section>
        <!--gridcolumn:3, gridrow:3-->
        <h2 class="sr-only">Footer</h3>
            <section>
                <h3>Saison</h3>
                <!--column1,row1-->
                <p>News</p>
                <p>Effectif</p>
                <p>Calendrier</p>
                <p>Classement</p>
            </section>

            <section>
                <h3>Club</h3>
                <!--column2,row1-->
                <p>Histoire</p>
                <p>Partenaires</p>
            </section>

            <section>
                <h3>Stade</h3>
                <!--column3,row1-->
                <p>Stade</p>
                <p>Plan d'accès</p>
            </section>
    </section>
    <section>
        <!--row2-->
        <p>Reseaux</p>
    </section>

    <section>
        <!--row3-->
        <p>Mentions legale</p>
    </section>
</footer>