<footer id="footer">

    <section>
        <!--gridcolumn:3, gridrow:3-->
        <h2 class="sr-only">Footer</h2>
            <section>
                <h3>Saison</h3>
                <!--column1,row1-->
                <ul>
                    <li>News</li>
                    <li>Effectif</li>
                    <li>Calendrier</li>
                    <li>Classement</li>
                </ul>
            </section>

            <section>
                <h3>Club</h3>
                <!--column2,row1-->
                <p>Histoire</p>
                <p>Partenaires</p>
                <p><a href="/res03-projet-final/ProjetPerso/contact">Contact</a></p>
            </section>

            <section>
                <h3>Infrastructure</h3>
                <!--column3,row1-->
                <p>Stade</p>
                <p>Plan d'accès</p>
            </section>
    </section>
    <section>
        <!--row2-->
        <h3>Réseaux Sociaux</h3>
        <span class="fa-brands fa-2xs fa-facebook fa-beat"></span>
        <span class="fa-brands fa-2xs fa-instagram fa-beat"></span>
        <span class="fa-brands fa-2xs fa-twitter fa-beat"></span>
        <span class="fa-brands fa-2xs fa-tiktok fa-beat "></span>
    </section>

    <section>
        <!--row3-->
        <h2 class="sr-only">Mentions Légales</h2>
        <p>Copyright . Arnaud Deletre</p>
    </section>
    
    
</footer>