<footer id="footer">

    <section>
        <!--gridcolumn:3, gridrow:3-->
        <h2 class="sr-only">Footer</h2>
            <section>
                <h3>Saison</h3>
                <!--column1,row1-->
                <ul>
                    <li><a href="/res03-projet-final/ProjetPerso/articles">News</a></li>
                    <li><a href="/res03-projet-final/ProjetPerso/equipes/effectif">Effectif</a></li>
                    <li>Calendrier</li>
                    <li>Classement</li>
                </ul>
            </section>

            <section>
                <h3>Club</h3>
                <!--column2,row1-->
                <p><a href="/res03-projet-final/ProjetPerso/le-club">Histoire</a></p>
                <p>Partenaires</p>
                <p><a href="/res03-projet-final/ProjetPerso/contact">Contact</a></p>
            </section>

            <section>
                <h3>Infrastructure</h3>
                <!--column3,row1-->
                <p><a href="/res03-projet-final/ProjetPerso/le-club/infrastructure">Stade</a></p>
                <p><a href="/res03-projet-final/ProjetPerso/le-club/infrastructure">Plan d'accès</a></p>
            </section>
    </section>
    <section>
        <!--row2-->
        <h3>Réseaux Sociaux</h3>
        <a href="https://www.facebook.com/USSainteMarie"><span class="fa-brands fa-2xs fa-facebook fa-beat"></span></a>
        <a href="https://www.instagram.com/ussm35600/"><span class="fa-brands fa-2xs fa-instagram fa-beat"></span></a>
        <a href="https://twitter.com/us_sainte?lang=fr"><span class="fa-brands fa-2xs fa-twitter fa-beat"></span></a>
    </section>

    <section>
        <!--row3-->
        <h2 class="sr-only">Mentions Légales</h2>
        <p>© 2023 Arnaud-Dlt. Tous droits réservés.</p>
    </section>
    
    
</footer>