<header>
    <nav>
        <h2 class="sr-only">Nav</h2>
        <figure>
            <a href=""><img src="../assets/img/ecusson.jpg"></a>
        </figure>
        <ul>
            <li>
                <a href="https://arnauddeletre.sites.3wa.io/res03-projet-final/ProjetPerso/">Accueil</a>
            </li>
            
            <li>
                <a href="https://arnauddeletre.sites.3wa.io/res03-projet-final/ProjetPerso/le-club">Le Club</a>
            </li>
            
            <li>
                <a href="https://arnauddeletre.sites.3wa.io/res03-projet-final/ProjetPerso/equipes">Equipes</a>
            </li>
            
            <li>
                <a href="https://arnauddeletre.sites.3wa.io/res03-projet-final/ProjetPerso/galerie">Galerie</a>
            </li>
            
            <li>
                <a href="https://arnauddeletre.sites.3wa.io/res03-projet-final/ProjetPerso/events">Evenements</a>
            </li>
            
            <li>
                <a href="">Boutique (en cours)</a>
            </li>
            
            <li>
                <a href="https://arnauddeletre.sites.3wa.io/res03-projet-final/ProjetPerso/contact">Contact</a>
            </li>
        </ul>
    </nav>
</header>