<header>
    <nav>
        <h2 class="sr-only">Nav</h2>
        <figure>
            <a href=""><img src="../assets/img/ecusson.jpg"></a>
        </figure>
        <ul>
            <li>
                <a href="">Accueil</a>
            </li>
            
            <li>
                <a href="">Le Club</a>
            </li>
            
            <li>
                <a href="">Equipes</a>
            </li>
            
            <li>
                <a href="">Galerie</a>
            </li>
            
            <li>
                <a href="">Evenements</a>
            </li>
            
            <li>
                <a href="">Boutique (en cours)</a>
            </li>
            
            <li>
                <a href="">Contact</a>
            </li>
        </ul>
    </nav>
</header>