<header id="publicNav">
    <nav>
        <h2 class="sr-only">Nav</h2>
        <figure>
            <a href=""><img src="assets/img/ecusson.jpg" alt="logo"></a>
        </figure>
        <ul>
            <li>
                <a href="/res03-projet-final/ProjetPerso/">Accueil</a>
            </li>
            
            <li>
                <a href="/res03-projet-final/ProjetPerso/le-club">Le Club</a>
                <ul>
                    <li><a href="/res03-projet-final/ProjetPerso/le-club/histoire">Histoire</a></li>
                    <li><a href="/res03-projet-final/ProjetPerso/le-club/organigramme">Organigramme</a></li>
                    <li><a href="/res03-projet-final/ProjetPerso/le-club/infrastructure">Infrastructure</a></li>
                </ul>
            </li>
            
            <li>
                <a href="/res03-projet-final/ProjetPerso/articles">Articles</a>
            </li>

            <li>
                <a href="/res03-projet-final/ProjetPerso/equipes">Equipes</a>
                <ul>
                    <li><a href="/res03-projet-final/ProjetPerso/equipes/effectif">Effectif</a></li>
                    <li><a href="">Senior A</a></li>
                    <li><a href="">Senior B</a></li>
                    <li><a href="">Vétérans</a></li>
                    <li><a href="">Jeunes</a></li>
                </ul>
            </li>
            
            <li>
                <a href="/res03-projet-final/ProjetPerso/galerie">Galerie</a>
            </li>
            
            <li>
                <a href="/res03-projet-final/ProjetPerso/events">Evenements</a>
            </li>
            
            <li>
                <a href="">Boutique (en cours)</a>
            </li>
            
            <li>
                <a href="/res03-projet-final/ProjetPerso/contact">Contact</a>
            </li>
            
        </ul>
        
        
    </nav>
</header>