<main id="allArticles">
    <h1>Tous les articles</h1>
    <select>
        <option>-Trier par...</option>
        <option>Date récentes</option>
        <option>Date ancienne</option>
    </select>
    <ul>
        <li>
            <article>
                <header>
                    <figure>
                        <img src=""  alt="photo de l'article">
                    </figure>
                </header>
                <main>
                    <h3>Title</h3>
                    <p>Content</p>
                </main>
                <button>Lire l'article</button>
            </article>
        </li>
    </ul>
</main>