<main id="allArticles">
    <h2>Tous les articles</h2>
    <!--<select>-->
    <!--    <option>-Trier par...</option>-->
    <!--    <option>Date récentes</option>-->
    <!--    <option>Date ancienne</option>-->
    <!--</select>-->
    <section>
        <h3 class="sr-only">Liste des articles</h3>
        <ul>
        <?php foreach($data['articles'] as $article){?>
            <li>
                <article class="hoverZoom">
                    <h3 class="sr-only">Article</h3>
                    <header>
                        <figure>
                            <img src="<?= $article->getPicture(); ?>"  alt="photo de l'article">
                        </figure>
                    </header>
                    <section>
                        <h4><?= $article->getTitle() ?></h4>
                        <p><?= $article->getDescription() ?></p>
                    </section>
                    <a href="/res03-projet-final/ProjetPerso/articles/single-article/<?= $article->getId();?>">
                        <button class="seeBtn">Lire l'article</button>
                    </a>
                </article>
            </li>
            <?php } ?>
        </ul>
    </section>
</main>