<main id="allArticles">
    <h2>Tous les articles</h2>
    <select>
        <option>-Trier par...</option>
        <option>Date récentes</option>
        <option>Date ancienne</option>
    </select>
    <section>
        <ul>
        <?php foreach($data['articles'] as $article){?>
            <li>
                <article>
                    <header>
                        <figure>
                            <img src="<?= $article->getPicture() ?>"  alt="photo de l'article">
                        </figure>
                    </header>
                    <main>
                        <h3><?= $article->getTitle() ?></h3>
                        <p><?= $article->getDescription() ?></p>
                    </main>
                    <button class="seeBtn">Lire l'article</button>
                </article>
            </li>
            <?php } ?>
        </ul>
    </section>
</main>