<main id="le-club-infrastructure">
    <h1>Infrastructure</h1>
    <section>
        <h2>Stade Henri Lucas</h2>
        <figure>
            <img src="/res03-projet-final/ProjetPerso/assets/img/club/stade_henri_lucas.jpg" alt="Stade Henri Lucas">
        </figure>
    </section>
    
    <section>
        <h2>Plan d'accès</h2>
        <section>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2685.7822749913535!2d-2.0048530451764264!3d47.68864816008163!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x480f754965c5ddc9%3A0xedee8604f62f98da!2sTerrain%20de%20Football!5e0!3m2!1sfr!2sfr!4v1681384212744!5m2!1sfr!2sfr" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </section>
    </section>
    
    <section>
        <h2>Stade de la Roche (terrain d'entrainement)</h2>
        <figure>
            <img src="/res03-projet-final/ProjetPerso/assets/img/club/stade_roche.jpg" alt="Stade de la Roche(entrainement)">
        </figure>
    </section>
    
    <section>
        <h2>Clubhouse</h2>
        <figure>
            <img src="" alt="">
        </figure>
    </section>
</main>
