<main id="le-club-organigramme">
    
    <section>
        <figure>
            <img src="" alt="">
        </figure>
        <p>image</p>
    </section>
    <h1>Organigramme</h1>
    <section>
        <section id="president">
            <article>
                <section>
                    <h2>Nom prenom</h2>
                    <h3>Poste</h3>
                </section>
            </article>
        </section>
        
        <section id="vice-president">
            <article>
                <section>
                    <h2>Nom prenom</h2>
                    <h3>Poste</h3>
                </section>
            </article>
        </section>
        
        <section id="tresorier">
            <article>
                <section>
                    <h2>Nom prenom</h2>
                    <h3>Poste</h3>
                </section>
            </article>
        </section>
        
        <section id="secretaire">
            <article>
                <section>
                    <h2>Nom prenom</h2>
                    <h3>Poste</h3>
                </section>
            </article>
        </section>
        
        <section id="responsable-senior">
            <article>
                <section>
                    <h2>Nom prenom</h2>
                    <h3>Poste</h3>
                </section>
            </article>
        </section>
        
        <section id="responsable-seniorA">
            <article>
                <section>
                    <h2>Nom prenom</h2>
                    <h3>Poste</h3>
                </section>
            </article>
        </section>
        
        <section id="responsable-seniorB">
            <article>
                <section>
                    <h2>Nom prenom</h2>
                    <h3>Poste</h3>
                </section>
            </article>
        </section>
        
        <section id="responsable-veterans">
            <article>
                <section>
                    <h2>Nom prenom</h2>
                    <h3>Poste</h3>
                </section>
            </article>
        </section>
        
        <section id="responsable-jeunes">
            <article>
                <section>
                    <h2>Nom prenom</h2>
                    <h3>Poste</h3>
                </section>
            </article>
        </section>
    </section>
</main>
