<main id="le-club-infrastructure">
    <h1>Infrastructure</h1>
    <section>
        <h2>Stade Henri Lucas</h2>
        <figure>
            <img src="" alt="">
        </figure>
    </section>
    
    <section>
        <h2>Stade de la Roche (terrain d'entrainement)</h2>
        <figure>
            <img src="" alt="">
        </figure>
    </section>
    
    <section>
        <h2>Clubhouse</h2>
        <figure>
            <img src="" alt="">
        </figure>
    </section>
    
    <section>
        <h2>Plan d'accès</h2>
        <figure>
            <img src="" alt="">
        </figure>
    </section>
</main>
