<main id="le-club">
    <h2>Présentation du Club</h2>
    
    <section>
        <h3 class="sr-only">Histoire du club</h3>
        <section>
            <h3>Histoire <span class="fa-solid fa-landmark fa-xs"></span></h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>
        </section>
        <figure>
            <img src="https://picsum.photos/300" alt="Photo d'époque du club">
        </figure>
    </section>
    
    <section>
        <h3 class="sr-only">Bureau du club</h3>
        <section>
            <h3>Bureau <span class="fa-solid fa-people-group fa-xs"></span></h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letras</p>
            <a href="/res03-projet-final/ProjetPerso/le-club/organigramme">Voir l'organigramme</a>
        </section>
        <figure>
            <img src="https://picsum.photos/300" alt="Photo de l'équipe du bureau">
        </figure>
    </section>
    
    <section>
        <h3 class="sr-only">Infrastructure du club</h3>
        <section>
            <h3>Infrastructure <span class="fa-solid fa-house fa-xs"></span></h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letras</p>
            <a href="/res03-projet-final/ProjetPerso/le-club/infrastructure">Voir les infrastructure du club</a>
        </section>
        <figure>
            <img src="https://picsum.photos/300">
        </figure>
    </section>
</main>
