<main id="contact">
    <h2>Contactez-nous</h2>

    <form action="" method="POST" id="contactForm">
        
        <fieldset>
            <label>Prenom</label>
            <input type="text" name="firstname" id="contactFirstname">
        </fieldset>
        
        <fieldset>
            <label>Nom</label>
            <input type="text" name="lastname" id="contactLastname">
        </fieldset>
        
        <fieldset>
            <label>Email</label>
            <input type="email" name="email" id="contactEmail">
        </fieldset>
        
        <fieldset>
            <label>Objet</label>
            <select>
                <option>---</option>
                <option>Demande de licence</option>
                <option>Informations</option>
                <option>Championnat</option>
                <option>Autre</option>
            </select>
        </fieldset>
        
        <fieldset>
            <label>Message</label>
            <input type="textarea" name="contactMessage" id="contactMessage">
        </fieldset>
        
        <input type="submit" name="contactBtn">
    </form>
</main>