<?php 
var_dump($_POST);
$n1=$_POST['n°1'];
$n2=$_POST['n°2'];
$n3=$_POST['n°3'];
$n4=$_POST['n°4'];
$n5=$_POST['n°5'];
$n6=$_POST['n°6'];
$n7=$_POST['n°7'];
$n8=$_POST['n°8'];
$n9=$_POST['n°9'];
$n10=$_POST['n°10'];
$n11=$_POST['n°11'];
$n12=$_POST['n°12'];
$n13=$_POST['n°13'];
$n14=$_POST['n°14'];

?>

<main id="publicConvoc">
    <h2>convocations</h2>
    <table>
        <thead>
            <th>N°</th>
            <th>Joueur</th>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td><?= $n1 ?></td>
            </tr>
            
            <tr>
                <td>2</td>
                <td><?= $n2 ?></td>
            </tr>
            
            <tr>
                <td>3</td>
                <td><?= $n3 ?></td>
            </tr>
            
            <tr>
                <td>4</td>
                <td><?= $n4 ?></td>
            </tr>
            
            <tr>
                <td>5</td>
                <td><?= $n5 ?></td>
            </tr>
            
            <tr>
                <td>6</td>
                <td><?= $n6 ?></td>
            </tr>
            
            <tr>
                <td>7</td>
                <td><?= $n7 ?></td>
            </tr>
            
            <tr>
                <td>8</td>
                <td><?= $n8 ?></td>
            </tr>
            
            <tr>
                <td>9</td>
                <td><?= $n9 ?></td>
            </tr>
            
            <tr>
                <td>10</td>
                <td><?= $n10 ?></td>
            </tr>
            
            <tr>
                <td>11</td>
                <td><?= $n11 ?></td>
            </tr>
            
            <tr>
                <td>12</td>
                <td><?= $n12 ?></td>
            </tr>
            
            <tr>
                <td>13</td>
                <td><?= $n13 ?></td>
            </tr>
            
            <tr>
                <td>14</td>
                <td><?= $n14 ?></td>
            </tr>
        </tbody>
    </table>
</main>