<main id="effectif">
<a href="/res03-projet-final/ProjetPerso/equipes"><| Equipes</a>
<h1>Effectif</h1>
    <nav>
        <h3 class="sr-only">Lien vers les postes</h3>
        <ul>
            <li><a href="#gardiens">Gardiens</a></li>
            <li><a href="#defenseurs">Defenseurs</a></li>
            <li><a href="#milieux">Milieu</a></li>
            <li><a href="#attaquants">Attaquants</a></li>
        </ul>
    </nav>
    
    <section>
        <h2 id="gardiens">Gardien</h2>
        <ul>
            <?php 
            foreach($data['goalkeepers'] as $goalkeeper){?>
            <li>
                <article>
                    <h3 class="sr-only">Gardien</h3>
                    <header>
                        <figure>
                            <img src="./../assets/img/joueurs/<?= $goalkeeper->getProfilImg() ?>" alt="Photo <?= $goalkeeper->getFirstname() ?> <?= $goalkeeper->getLastname() ?>">
                        </figure>
                    </header>
                    <section>
                        <h3><?= $goalkeeper->getFirstname() ?> <?= $goalkeeper->getLastname() ?></h3>
                    </section>
                    <a href="/res03-projet-final/ProjetPerso/equipes/effectif/player-profil/<?= $goalkeeper->getId();?>">
                        <button>Voir joueur</button>
                    </a>
                </article>
            </li>
            <?php } ?>
        </ul>
        <h2 id="defenseurs">Défenseurs</h2>
        <ul>
            <?php 
            foreach($data['defenders'] as $defender){?>
            <li>
                <article>
                    <h3 class="sr-only">Défenseur</h3>
                    <header>
                        <figure>
                            <img src="./../assets/img/joueurs/<?= $defender->getProfilImg() ?>" alt="photo du joueur">
                        </figure>
                    </header>
                    <section>
                        <h3><?= $defender->getFirstname() ?> <?= $defender->getLastname() ?></h3>
                    </section>
                    <a href="/res03-projet-final/ProjetPerso/equipes/effectif/player-profil/<?= $defender->getId();?>">
                        <button>Voir joueur</button>
                    </a>
                </article>
            </li>
            <?php } ?>
        </ul>
        <h2 id="milieux">Milieux</h2>
        <ul>
            <?php 
            foreach($data['midfielders'] as $midfielder){?>
            <li>
                <article>
                    <h3 class="sr-only">Milieu</h3>
                    <header>
                        <figure>
                            <img src="./../assets/img/joueurs/<?= $midfielder->getProfilImg() ?>" alt="photo du joueur">
                        </figure>
                    </header>
                    <section>
                        <h3><?= $midfielder->getFirstname() ?> <?= $midfielder->getLastname() ?></h3>
                    </section>
                    <a href="/res03-projet-final/ProjetPerso/equipes/effectif/player-profil/<?= $midfielder->getId();?>">
                        <button>Voir joueur</button>
                    </a>
                </article>
            </li>
            <?php } ?>
        </ul>
        <h2 id="attaquants">Attaquants</h2>
        <ul>
            <?php 
            foreach($data['strikers'] as $strikers){?>
            <li>
                <article>
                    <h3 class="sr-only">Attaquant</h3>
                    <header>
                        <figure>
                            <img src="./../assets/img/joueurs/<?= $strikers->getProfilImg() ?>" alt="photo du joueur">
                        </figure>
                    </header>
                    <section>
                        <h3><?= $strikers->getFirstname() ?> <?= $strikers->getLastname() ?></h3>
                    </section>
                    <a href="/res03-projet-final/ProjetPerso/equipes/effectif/player-profil/<?= $strikers->getId();?>">
                        <button>Voir joueur</button>
                    </a>
                </article>
            </li>
            <?php } ?>
        </ul>
    </section>
</main>