<main id="events">
    <h2>Les Évenements du club</h2>
    <section>
        <h3 class="sr-only">Les différents évenements du club</h3>
        <section>
            <h4>Le Couscous</h4>
            <figure>
                <img src="/res03-projet-final/ProjetPerso/assets/img/events/couscous_2022.jpg" alt="">
            </figure>
        </section>
        
        <section>
            <h4>L'OktoberFest</h4>
            <figure>
                <img src="/res03-projet-final/ProjetPerso/assets/img/events/oktoberfest.jpg" alt="">
            </figure>
        </section>
        
        <section>
            <h4>La Fête du Pont du Grand Pas</h4>
            <img src="/res03-projet-final/ProjetPerso/assets/img/events/" alt="">
        </section>
    </section>
</main>