<main id="events">
    <h2>Les Évenements du club</h2>
    <section>
        <section>
            <h3>Le Couscous</h3>
            <figure>
                <img src="/res03-projet-final/ProjetPerso/assets/img/events/couscous_2022.jpg" alt="">
            </figure>
        </section>
        
        <section>
            <h3>L'OktoberFest</h3>
            <figure>
                <img src="/res03-projet-final/ProjetPerso/assets/img/events/oktoberfest.jpg" alt="">
            </figure>
        </section>
        
        <section>
            <h3>La Fête du Pont du Grand Pas</h3>
            <img src="/res03-projet-final/ProjetPerso/assets/img/events/" alt="">
        </section>
    </section>
</main>