<main id="galerie">
    <h2>Galerie</h2>
    <select>
        <option>-Trier par...</option>
        <option>Date récentes</option>
        <option>Date ancienne</option>
    </select>
    <section>
        <ul>
        <!--foreach($data['albums'] as $album){-->
            <li>
                <article>
                    <header>
                        <figure>
                            <!--<img src=" $album->getPicture()"  alt="photo de l'album">-->
                        </figure>
                    </header>
                    <main>
                        <h3>test</h3>
                        <p>test</p>
                    </main>
                    <button class="seeBtn">Voir les photos</button>
                </article>
            </li>
        <!--balise php-->
        </ul>
    </section>
</main>