<main id="galerie">
    <h2>Galerie</h2>
    <!--<select>-->
    <!--    <option>-Trier par...</option>-->
    <!--    <option>Date récentes</option>-->
    <!--    <option>Date ancienne</option>-->
    <!--</select>-->
    <section>
        <h3 class="sr-only">Liste des albums photo</h3>
        <ul>
        <!--foreach($data['albums'] as $album){-->
            <li>
                <article  class="hoverZoom">
                    <h3 class="sr-only">Album 1</h3>
                    <header>
                        <figure>
                            <!--<img src=" $album->getPicture()"  alt="photo de l'album">-->
                        </figure>
                    </header>
                    <section>
                        <h4>Titre Album 1</h4>
                        <p>Description Album 1</p>
                    </section>
                    <button class="seeBtn">Voir les photos</button>
                </article>
            </li>
        <!--balise php-->
        </ul>
    </section>
</main>