<main id="home">
    <figure>
        <img src="" alt="photo-aléatoire">
    </figure>
    <section>
        <section>
            <h2>Prochain match</h2>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script><script>if(!window._rsz){window._rsz=function(){var i=iFrameResize({checkOrigin:false,interval:100});};if(document.readyState!="loading"){_rsz()}else{document.addEventListener("DOMContentLoaded",_rsz)}}</script><iframe id="64070604bd0ad9680e6ade48" src="https://scorenco.com/widget/64070604bd0ad9680e6ade48/?auto_height=true" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;" scrolling="no"></iframe>
        </section>
    </section>

    <section>
        <section>
            <h2>Article le plus récent</h2>
        </section>
        <section>
            <h2>Autres articles</h2>
            <article><p>article 1</p></article>
            <article><p>article 2</p></article>
            <article><p>article 3</p></article>
        </section>
        <button>Voir Plus</button>
    </section>
    
    <section>
        <section>
            <h2>Album1</h2>
        </section>
        
        <section>
            <h2>Album2</h2>
        </section>
        <button>Voir Albums</button>
    </section>
</main>