<main id="home">
    <figure>
        <img src="/res03-projet-final/ProjetPerso/assets/img/backgrd_USSM.jpg" alt="photo-aléatoire">
    </figure>
    <section>
        <h2 class="sr-only">Matchs à venir</h2>
        <section>
            <h2>Prochains matchs</h2>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script><script>if(!window._rsz){window._rsz=function(){var i=iFrameResize({checkOrigin:false,interval:100});};if(document.readyState!="loading"){_rsz()}else{document.addEventListener("DOMContentLoaded",_rsz)}}</script><iframe id="64070604bd0ad9680e6ade48" src="https://scorenco.com/widget/64070604bd0ad9680e6ade48/?auto_height=true" style="display: block; width: 100%; overflow: auto; margin: auto; border-width: 0px;" scrolling="no"></iframe>
        </section>
    </section>

    <section>
        <h2 class="sr-only">Articles</h2>
        <section>
            <h2>Dernières Actualités</h2>
            <article>
                <h2 class="sr-only"><?= $data['lastArticle']->getTitle() ?></h2>
                <header>
                    <figure>
                        <img src="" alt="photo article">
                    </figure>
                </header>
                <section>
                    <h3><?= $data['lastArticle']->getTitle() ?></h3>
                    <p><?= $data['lastArticle']->getDescription() ?></p>
                    <button>Voir cet article</button>
                </section>
            </article>
            
        </section>
        <section>
            <h2>Autres actualités</h2>
            <article>
                <h2 class="sr-only"><?= $data['lastArticle']->getTitle() ?></h2>
                <figure>
                    <img src="" alt="">
                </figure>
                <section>
                    <h3>Titre</h3>
                    <p>Description</p>
                </section>
            </article>
            
            <article>
                <h2 class="sr-only"><?= $data['lastArticle']->getTitle() ?></h2>
                <figure>
                    <img src="" alt="">
                </figure>
                <section>
                    <h3>Titre</h3>
                    <p>Description</p>
                </section>
            </article>
            
            <article>
                <h2 class="sr-only"><?= $data['lastArticle']->getTitle() ?></h2>
                <figure>
                    <img src="" alt="">
                </figure>
                <section>
                    <h3>Titre</h3>
                    <p>Description</p>
                </section>
            </article>
            
        </section>
        <button>Voir Plus</button>
    </section>
    
    <section>
        <h2 class="sr-only">Aperçu galerie</h2>
        <section>
            <h2>Album1</h2>
        </section>
        
        <section>
            <h2>Album2</h2>
        </section>
        <button>Voir Albums</button>
    </section>
</main>