<main id="login">
    <h2>Se connecter</h2>
    <form action="admin" method="post" class="form-floating mb-3">
        <label>Email</label>
        <input type="email" name="loginEmail" class="form-control" id="floatingInput" required>
        <label>Mot de passe</label>
        <input type="password"  name="loginPassword" class="form-control" id="floatingPassword" required>
        <input type="submit" name="loginBtn" value="Se connecter">
    </form>
</main>
