<main id="playerProfil">
    <h2><?php $data['players']->getFirstname(); $data['players']->getLastname(); ?></h2>
    <h3><?php $data['players']->getPosition()?></h3>
    <section>
        <?php var_dump($data) ?>
        <figure>
            <img src="<?php $data['players']->getProfilImg()?>" alt="photo du joueur">
        </figure>
    </section>
    <section>
        <h3>Parcours</h3>
        <p><?php $data['players']->getBio()?></p>
    </section>
</main>