<main id="playerProfil">
    <a href="/res03-projet-final/ProjetPerso/equipes/effectif"><| Effectif</a>
    
    <section>
    <h2><?= $data['player']->getFirstname()?> <?= $data['player']->getLastname(); ?></h2>
    <h3><?= $data['player']->getPosition()?></h3>
    
    <figure>
        <img src="/res03-projet-final/ProjetPerso/assets/img/joueurs/<?= $data['player']->getProfilImg() ?>" alt="Photo <?= $data['player']->getFirstname() ?> <?= $data['player']->getLastname() ?>">
    </figure>
    </section>
    
    <section>
        <h3>Parcours</h3>
        <p><?= $data['player']->getBio()?></p>
    </section>
</main>