<main id="teams">
    <!--<figure>-->
    <!--    <img src="/res03-projet-final/ProjetPerso/assets/img/backgrd_USSM.jpg" alt="Photo de tous les joueurs">-->
    <!--</figure>-->
    <h1>Toutes les équipes</h1>
    <section>
        <h2><a href="/res03-projet-final/ProjetPerso/equipes/effectif">Voir l'effectif complet ></a></h2>
        <ul>
            <?php 
            foreach($data['teams'] as $team){ ?>
                <li>
                    <article>
                        <header>
                            <h2><?= $team->getName()?></h2>
                        </header>
                        <section>
                            <h3 class="sr-only">Photo d'équipe</h3>
                            <figure>
                                <img src="/res03-projet-final/ProjetPerso/assets/img/<?= $team->getPicture()?>" alt="Photo de l'équipe">
                            </figure>
                        </section>
                    </article>
                </li>
            <?php } ?>
        </ul>
        <p><a href="/res03-projet-final/ProjetPerso/equipes/résumé-saisonA/">Résumé Saison equipe A</a></p>
        <p><a href="/res03-projet-final/ProjetPerso/equipes/résumé-saisonB/">Résumé Saison equipe B</a></p>
    </section>
</main>